### PR TITLE
Set popover vc barButtonItem to fix crash

### LINKED ISSUE #287: Crash on iOS 9.3 attempting to show map style pop up
### Description
Map Style popup presentation appears to not be support on versions previous to iOS 10.

### Steps to Reproduce
Load sample app on iOS 9.3
Attempt to launch Map Style switcher.
Note crash

### Logs
```
2017-04-24 11:41:59.702 ios-sdk[253:7765] *** Terminating app due to uncaught exception 'NSGenericException', reason: 'Your application has presented a UIAlertController (<UIAlertController: 0x15a7f600>) of style UIAlertControllerStyleActionSheet. The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'
*** First throw call stack:
(0x2103791b 0x207d2e17 0x25ea3485 0x25903e93 0x25901db3 0x2585b4c9 0x258677db 0x255a5b1d 0x20ff96c9 0x20ff79cd 0x20ff7dff 0x20f47229 0x20f47015 0x22537ac9 0x2561b189 0x1548f4 0x20bef873)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

### Mapzen SDK & iOS Version
Sample App 0.4.0
iOS 9.3.5
iPad Mini 1

### PR DESCRIPTION
**Pull request by sarahlensing**
### Overview
Sets a `barButtonItem` for all `UIAlertController` action sheets.

### Proposed Changes
Fixes crash on iPads

Fixes #287

### CODE REVIEW

File: SampleApp/DemoMapViewController.swift [hunk 1]
```diff
@@ -86,31 +88,26 @@ class DemoMapViewController:  SampleMapViewController, MapMarkerSelectDelegate {
...
-      self.updateLocale(Locale.init(identifier: "es_ES"))
-    }))
-    actionSheet.addAction(UIAlertAction.init(title: "Korean", style: .default, handler: { [unowned self] (action) in
-      self.updateLocale(Locale.init(identifier: "ko_KR"))
-    }))
-    actionSheet.addAction(UIAlertAction.init(title: "Italian", style: .default, handler: { [unowned self] (action) in
-      self.updateLocale(Locale.init(identifier: "it_IT"))
-    }))
+    for (actionTitle, languageIdentifier) in languageIdByActionSheetTitle {
+      actionSheet.addAction(UIAlertAction.init(title: actionTitle, style: .default, handler: { [unowned self] (action) in
```
Comment (msmollin) [inline SampleApp/DemoMapViewController.swift]: Kind of obnoxious you have to do it this way and that `UIAlertController` won't accept an array of actions. Would be a good use for `map()` function if that were the case. Ah well.
